inherit_from: .rubocop_todo.yml

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/BlockComments:
  Exclude:
    - 'spec/**/*'

Naming/MethodName:
  Exclude:
    - 'lib/jukebox/cukes.rb'

Lint/RescueException:
  Exclude:
    - 'lib/jukebox/client.rb'

Metrics/MethodLength:
  Exclude:
    - 'lib/jukebox/core_ext/hash.rb'
