Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/BlockComments:
  Exclude:
    - 'spec/**/*'

Naming/MethodName:
  Exclude:
    - 'lib/jukebox/cukes.rb'

Lint/RescueException:
  Exclude:
    - 'lib/jukebox/client.rb'