---
version: 2

references:
  save_repo_cache: &save_repo_cache
    save_cache:
      key: v1-jukebox-repo-{{ .Branch }}
      paths:
        - .

  restore_repo_cache: &restore_repo_cache
    restore_cache:
      key: v1-jukebox-repo-{{ .Branch }}

  save_mvn_cache: &save_mvn_cache
    save_cache:
      key: v1-jukebox-deps-{{ checksum "project.clj" }}
      paths:
        - ~/.m2

  restore_mvn_cache: &restore_mvn_cache
    restore_cache:
      keys:
        - v1-jukebox-deps-{{ checksum "project.clj" }}

  deploy_config: &deploy_config
    docker:
      - image: circleci/clojure:lein-2.8.3
    working_directory: ~/jukebox

  build_config: &build_config
    docker:
      - image: circleci/clojure:lein-2.9.1
    working_directory: ~/jukebox

jobs:
  checkout_code:
    <<: *build_config
    steps:
      - <<: *restore_repo_cache
      - checkout
      - <<: *save_repo_cache

  checkout_tags:
    <<: *deploy_config
    steps:
      - <<: *restore_repo_cache
      # Workaround required for https://discuss.circleci.com/t/22437
      #
      # This is required to prevent the warning that appears about connecting
      # to a host for the first time when we attempt to fetch the tags from
      # github.
      #
      # The `add-key` script checks the fingerprint of the ssh key returned
      # by github against the fingerprint published below on their website
      # to protect against MITM attacks
      #
      #  https://help.github.com/en/articles/githubs-ssh-key-fingerprints
      #
      - run: |
          .circleci/bin/add-key github.com $GITHUB_SSH_FINGERPRINT
          git fetch --force origin "refs/tags/${CIRCLE_TAG}:refs/tags/${CIRCLE_TAG}"
          git checkout --force "$CIRCLE_TAG"
      - <<: *save_repo_cache

  deps:
    <<: *build_config
    steps:
      - <<: *restore_repo_cache
      - <<: *restore_mvn_cache
      - run:
          lein with-profiles +test deps
      - <<: *save_mvn_cache

  test:
    <<: *build_config
    steps:
      - <<: *restore_repo_cache
      - <<: *restore_mvn_cache
      - run:
          lein test

  deploy:
    <<: *deploy_config
    steps:
      - <<: *restore_repo_cache
      - <<: *restore_mvn_cache
      - run:
          name: Prepare signing key
          command: |
            echo $GPG_PRIVATE_KEY |base64 --decode |gpg --yes --batch --import

      - run:
          name: Deploy to Clojars
          command: |
            export LEIN_GPG=/home/circleci/jukebox/.circleci/bin/gpg
            export REAL_GPG=$(which gpg)

            lein do jar, pom, deploy clojars

  deploy_snapshot:
    <<: *deploy_config
    steps:
      # - <<: *restore_repo_cache
      - checkout
      - <<: *restore_mvn_cache
      - run:
          name: Deploy to Clojars
          command: |
            [ -z "$CLOJARS_USERNAME" ] || lein do jar, pom, deploy clojars

workflows:
  version: 2
  build_and_test:
    jobs:
      # - checkout_code
      # - deps:
      #     requires:
      #       - checkout_code
      # - test:
      #     requires:
      #       - deps
      - deploy_snapshot:
          context: clojars-deploy
          # requires:
          #   - test
          filters:
            tags:
              ignore: /.*/
            branches:
              ignore: /master/

  checkout_and_deploy:
    jobs:
      - checkout_tags:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
      - deploy:
          context: clojars-deploy
          requires:
            - checkout_tags
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
